#!/usr/bin/env bash

APP="trucksu" # name of your release
# LINK_SYS_CONFIG=/etc/trucksu.config

RELEASE_STORE=s3://AKIAI5ZQ4D5XPVYRB2DA@o0271BSt2JTd/z97dlPDExumUili++/bNT3hHJJ9:trucksu-releases

BUILD_HOST="159.203.50.253" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/git/trucksu/builds" # build directory on build host

STAGING_HOSTS="159.203.50.252" # staging / test hosts separated by space
STAGING_USER="root" # local user at staging hosts
TEST_AT="/test/trucksu" # deploy directory on staging hosts. default is DELIVER_TO

# TODO: Set production host
PRODUCTION_HOSTS="159.203.50.252" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/opt/trucksu" # deploy directory on production hosts

pre_erlang_clean_compile() {
  status "Running npm install and phoenix.digest" # log output prepended with "----->"
  __sync_remote " # runs the commands on the build host
    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
    set -e # fail if any command fails (recommended)
    cd '$BUILD_AT' # enter the build directory on the build host (required)
    # prepare something
    mkdir -p priv/static # required by the phoenix.digest task
    # run your custom task
    NODE_ENV=production npm install $SILENCE
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD do compile, trucksu.digest $SILENCE
  "
}
