defmodule Game.Packet.Ids do
  def client_changeAction, do: 0
  def client_sendPublicMessage, do: 1
  def client_logout, do: 2
  def client_requestStatusUpdate, do: 3
  def client_pong, do: 4
  def server_userID, do: 5
  def server_commandError, do: 6
  def server_sendMessage, do: 7
  def server_ping, do: 8
  def server_handleIRCUsernameChange, do: 9
  def server_handleIRCQuit, do: 10
  def server_userStats, do: 11
  def server_userLogout, do: 12
  def server_spectatorJoined, do: 13
  def server_spectatorLeft, do: 14
  def server_spectateFrames, do: 15
  def client_startSpectating, do: 16
  def client_stopSpectating, do: 17
  def client_spectateFrames, do: 18
  def server_versionUpdate, do: 19
  def client_errorReport, do: 20
  def client_cantSpectate, do: 21
  def server_spectatorCantSpectate, do: 22
  def server_getAttention, do: 23
  def server_notification, do: 24
  def client_sendPrivateMessage, do: 25
  def server_updateMatch, do: 26
  def server_newMatch, do: 27
  def server_disposeMatch, do: 28
  def client_partLobby, do: 29
  def client_joinLobby, do: 30
  def client_createMatch, do: 31
  def client_joinMatch, do: 32
  def client_partMatch, do: 33
#def erver_lobbyJoin_obsolete, do: = 34
#def erver_lobbyPart_obsolete, do: = 35
  def server_matchJoinSuccess, do: 36
  def server_matchJoinFail, do: 37
  def client_matchChangeSlot, do: 38
  def client_matchReady, do: 39
  def client_matchLock, do: 40
  def client_matchChangeSettings, do: 41
  def server_fellowSpectatorJoined, do: 42
  def server_fellowSpectatorLeft, do: 43
  def client_matchStart, do: 44
  def allPlayersLoaded, do: 45
  def server_matchStart, do: 46
  def client_matchScoreUpdate, do: 47
  def server_matchScoreUpdate, do: 48
  def client_matchComplete, do: 49
  def server_matchTransferHost, do: 50
  def client_matchChangeMods, do: 51
  def client_matchLoadComplete, do: 52
  def server_matchAllPlayersLoaded, do: 53
  def client_matchNoBeatmap, do: 54
  def client_matchNotReady, do: 55
  def client_matchFailed, do: 56
  def server_matchPlayerFailed, do: 57
  def server_matchComplete, do: 58
  def client_matchHasBeatmap, do: 59
  def client_matchSkipRequest, do: 60
  def server_matchSkip, do: 61
  def server_unauthorised, do: 62
  def client_channelJoin, do: 63
  def server_channelJoinSuccess, do: 64
  def server_channelInfo, do: 65
  def server_channelKicked, do: 66
  def server_channelAvailableAutojoin, do: 67
  def client_beatmapInfoRequest, do: 68
  def server_beatmapInfoReply, do: 69
  def client_matchTransferHost, do: 70
  def server_supporterGMT, do: 71
  def server_friendsList, do: 72
  def client_friendAdd, do: 73
  def client_friendRemove, do: 74
  def server_protocolVersion, do: 75
  def server_mainMenuIcon, do: 76
  def client_matchChangeTeam, do: 77
  def client_channelPart, do: 78
  def client_receiveUpdates, do: 79
  def server_topBotnet, do: 80
  def server_matchPlayerSkipped, do: 81
  def client_setAwayMessage, do: 82
  def server_userPanel, do: 83
  def iRC_only, do: 84
  def client_userStatsRequest, do: 85
  def server_restart, do: 86
  def client_invite, do: 87
  def server_invite, do: 88
  def server_channelInfoEnd, do: 89
  def client_matchChangePassword, do: 90
  def server_matchChangePassword, do: 91
  def server_silenceEnd, do: 92
  def client_specialMatchInfoRequest, do: 93
  def server_userSilenced, do: 94
  def server_userPresenceSingle, do: 95
  def server_userPresenceBundle, do: 96
  def client_userPresenceRequest, do: 97
  def client_userPresenceRequestAll, do: 98
  def client_userToggleBlockNonFriendPM, do: 99
  def server_userPMBlocked, do: 100
  def server_targetIsSilenced, do: 101
  def server_versionUpdateForced, do: 102
  def server_switchServer, do: 103
  def server_accountRestricted, do: 104
  def server_jumpscare, do: 105
  def client_matchAbort, do: 106
  def server_switchTourneyServer, do: 107
  def client_specialJoinMatchChannel, do: 108
  def client_specialLeaveMatchChannel, do: 109
end
